from django.urls import path, re_path
from . import views

urlpatterns = [
    path('login', views.login, name="admin_login"),
    path('logout', views.logout, name="admin_logout"),
    path('login/validate', views.validate_admin_login, name="validate_admin_login"),
    path('', views.dashboard, name="admin_dashboard"),
    path('message/<int:id>/send/<int:uid>', views.send_message_customers, name="admin_send_message_customers"),

    # ajax
    path('ajax/datatables/customers', views.admin_datatable_ajax_customers_list, name="admin_datatable_ajax_customers_list"),
    path('ajax/datatables/staffs', views.admin_datatable_ajax_staffs, name="admin_datatable_ajax_staffs"),
    path('ajax/datatables/managers', views.admin_datatable_ajax_managers, name="admin_datatable_ajax_managers"),
    path('ajax/datatables/customers/followup', views.admin_datatable_ajax_customers_followup, name="admin_datatable_ajax_customers_followup"),
    path('ajax/datatables/followup', views.admin_datatable_ajax_followup, name="admin_datatable_ajax_followup"),
    path('ajax/datatables/message', views.admin_datatable_ajax_message, name="admin_datatable_ajax_message"),
    path('ajax/datatables/purchases', views.admin_datatable_ajax_customers_purchases, name="admin_datatable_ajax_customers_purchases"),
    path('ajax/datatables/payments', views.admin_datatable_ajax_customers_payments, name="admin_datatable_ajax_customers_payments"),
    path('ajax/datatables/refunds', views.admin_datatable_ajax_customers_refunds, name="admin_datatable_ajax_customers_refunds"),
    path('ajax/datatables/extras', views.admin_datatable_ajax_customers_extras, name="admin_datatable_ajax_customers_extras"),
    path('ajax/datatables/subscriptions', views.admin_datatable_ajax_customers_subscriptions, name="admin_datatable_ajax_customers_subscriptions"),
    path('ajax/datatables/extraless', views.admin_datatable_ajax_customers_extraless, name="admin_datatable_ajax_customers_extraless"),
    path('ajax/datatables/vacations', views.admin_datatable_ajax_customers_vacations, name="admin_datatable_ajax_customers_vacations"),
    path('ajax/datatables/reports/payments', views.admin_datatable_ajax_payments_report, name="admin_datatable_ajax_payments_report"),
    path('ajax/delivery/info', views.get_delivery_info, name="admin_get_delivery_info"),
    path('ajax/purchase/info', views.get_purchase_info, name="admin_get_purchase_info"),
    path('ajax/routes/customers', views.get_customers_of_route, name="admin_get_customers_of_route"),
    path('ajax/message/customers/date', views.get_message_date_of_customer, name="admin_get_message_date_of_customer"),
    path('ajax/routes/route-order/save', views.save_route_order, name="admin_save_route_order"),
    path('ajax/routes/customers/change', views.change_customers_route, name="admin_change_customers_route"),
    path('ajax/routes/customers/assign', views.assign_customers_route, name="admin_assign_customers_route"),
    path('ajax/routes/customers/assignations/clear', views.clear_customers_route_assignation, name="admin_clear_customers_route_assignation"),
    path('ajax/routes/customers/assignations/clear/all', views.clear_all_route_assignation, name="admin_clear_all_route_assignation"),
    
    #edit
    path('customers/edit/<int:id>', views.customers_edit, name="admin_customers_edit"),
    path('staffs/edit/<int:id>', views.staffs_edit, name="admin_staffs_edit"),
    path('managers/edit/<int:id>', views.managers_edit, name="admin_managers_edit"),
    path('payments/edit/<int:id>', views.payments_edit, name="admin_payments_edit"),
    path('refunds/edit/<int:id>', views.refunds_edit, name="admin_refunds_edit"),
    path('extras/edit/<int:id>', views.extras_edit, name="admin_extras_edit"),
    path('followup/edit/<int:id>', views.followup_edit, name="admin_followup_edit"),
    path('subscriptions/<int:id>', views.subscriptions_edit, name="admin_subscriptions_edit"),
    path('vacations/<int:id>', views.vacations_edit, name="admin_vacations_edit"),
    path('extraless/<int:id>', views.extraless_edit, name="admin_extraless_edit"),
    
    # create
    path('customers/create', views.customers_create, name="admin_customers_create"),
    path('staffs/create', views.staffs_create, name="admin_staffs_create"),
    path('managers/create', views.managers_create, name="admin_managers_create"),
    path('payments/create', views.payments_create, name="admin_payments_create"),
    path('refunds/create', views.refunds_create, name="admin_refunds_create"),
    path('extras/create', views.extras_create, name="admin_extras_create"),
    path('subscriptions/create', views.subscriptions_create, name="admin_subscriptions_create"),
    path('extraless/create', views.extraless_create, name="admin_extraless_create"),
    path('vacations/create', views.vacations_create, name="admin_vacations_create"),
    path('message/create', views.message_create, name="admin_message_create"),
    path('followup/add', views.add_followup_customer, name="admin_add_followup_customer"),

    # views
    path('customers/transactions/purchases', views.customers_purchases, name="admin_customers_purchases"),
    path('customers/transactions/payments', views.customers_payments, name="admin_customers_payments"),
    path('customers/transactions/refunds', views.customers_refunds, name="admin_customers_refunds"),
    path('customers/transactions/extras', views.customers_extras, name="admin_customers_extras"),
    path('customers/transactions/<int:id>', views.customer_transactions, name="admin_customers_transactions"),
    path('customers/subscriptions', views.customer_subscriptions, name="admin_customers_subscriptions"),
    path('customers/extraless', views.customer_extraless, name="admin_customers_extraless"),
    path('customers/vacations', views.customer_vacations, name="admin_customers_vacations"),
    path('customers/list', views.customers_list, name="admin_customers_list"),
    path('staffs/list', views.staff_list, name="admin_staff_list"),
    path('managers/list', views.manager_list, name="admin_manager_list"),
    path('customers/followup', views.customers_followup, name="admin_customers_followup"),
    path('followup', views.followup, name="admin_followup"),
    path('message', views.message, name="admin_message"),
    path('message/<int:id>/customers', views.message_customers, name="admin_message_customers"),
    path('route/order', views.route_ordering, name="admin_route_ordering"),
    path('reports/payments', views.payments_report, name="admin_payments_report"),

    # delete
    path('customers/delete/<int:id>', views.customer_delete, name="admin_customer_delete"),
    path('staffs/delete/<int:id>', views.staff_delete, name="admin_staff_delete"),
    path('managers/delete/<int:id>', views.manager_delete, name="admin_manager_delete"),
    path('payments/delete/<int:id>', views.payment_delete, name="admin_payment_delete"),
    path('refunds/delete/<int:id>', views.refund_delete, name="admin_refund_delete"),
    path('extras/delete/<int:id>', views.extra_delete, name="admin_extra_delete"),
    path('subscriptions/delete/<int:id>', views.subscription_delete, name="admin_subscription_delete"),
    path('extraless/delete/<int:id>', views.extraless_delete, name="admin_extraless_delete"),
    path('vacation/delete/<int:id>', views.vacation_delete, name="admin_vacation_delete"),
    path('followup/remove/<int:id>', views.remove_customer_followup, name="admin_remove_customer_followup"),
    path('message/delete/<int:id>', views.delete_message, name="admin_delete_message"),
    path('followup/remove/all', views.remove_all_customer_followup, name="admin_remove_all_customer_followup"),

    # end
    path('subscriptions/end/<int:id>', views.subscription_end, name="admin_subscription_end"),
    path('vacations/end/<int:id>', views.vacation_end, name="admin_vacation_end"),
    path('extraless/end/<int:id>', views.extraless_end, name="admin_extraless_end"),
]