# Generated by Django 3.2.3 on 2022-02-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydata',
            name='is_extra',
            field=models.BooleanField(default=False),
        ),
    ]
