# Generated by Django 3.2.3 on 2021-06-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
