# Generated by Django 3.2.3 on 2021-10-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_followup_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraless',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
