# Generated by Django 3.2.3 on 2022-01-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_message_messagerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='manager',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
