# Generated by Django 3.2.3 on 2022-01-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_staff_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=250)),
                ('routes', models.ManyToManyField(to='users.Route')),
            ],
        ),
    ]
