# Generated by Django 3.2.3 on 2022-01-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='manager',
        ),
    ]
