# Generated by Django 3.2.3 on 2022-02-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220222_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='area',
            new_name='areae',
        ),
    ]
