# Generated by Django 3.2.3 on 2022-02-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_area_route_areae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='areae',
            new_name='area',
        ),
    ]
