# Generated by Django 3.2.3 on 2022-03-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220311_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraless',
            name='created_by',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('manager', 'Manager')], default='admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extraless',
            name='edited_by',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('manager', 'Manager')], default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
