# Generated by Django 3.2.3 on 2022-03-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20220311_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_by',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('admin', 'Admin'), ('manager', 'Manager')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='edited_by',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('admin', 'Admin'), ('manager', 'Manager')], max_length=50, null=True),
        ),
    ]
