# Generated by Django 3.2.3 on 2022-06-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20220311_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='transaction_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refund',
            name='transaction_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_transaction',
            field=models.IntegerField(default=0),
        ),
    ]
