# Generated by Django 3.2.3 on 2022-06-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20220605_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_transaction',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
