# Generated by Django 3.2.3 on 2022-06-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_last_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_transaction',
            field=models.IntegerField(default=0),
        ),
    ]
