# Generated by Django 3.2.3 on 2022-06-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_last_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_transaction',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
