# Generated by Django 3.2.3 on 2022-06-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_user_last_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='delivery_name',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
