# Generated by Django 3.2.3 on 2021-11-29 09:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_email'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 9, 23, 35, 964413, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='HandOver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 11, 29, 9, 23, 35, 985455, tzinfo=utc))),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff', verbose_name='staff')),
            ],
        ),
    ]
