# Generated by Django 3.2.3 on 2021-11-29 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20211129_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 11, 29, 13, 45, 41, 628779, tzinfo=utc))),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('note', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='collection',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 13, 45, 41, 610695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='handover',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 13, 45, 41, 628252, tzinfo=utc)),
        ),
    ]
