# Generated by Django 3.2.3 on 2021-12-22 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20211130_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 22, 13, 7, 11, 374114, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 22, 13, 7, 11, 393247, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='handover',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 22, 13, 7, 11, 392396, tzinfo=utc)),
        ),
    ]
