# Generated by Django 3.2.3 on 2021-07-18 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_followup_last_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRefund',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reason', models.CharField(blank=True, choices=[('not delivered', 'Not delivered'), ('leaked', 'Leaked'), ('Spoiled', 'Spoiled')], max_length=50, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.product', verbose_name='extra product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='refund user')),
            ],
        ),
        migrations.CreateModel(
            name='DPurchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.staff', verbose_name='delivery boy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.product', verbose_name='purchase product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='purchase user')),
            ],
        ),
        migrations.CreateModel(
            name='DPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('mode', models.CharField(blank=True, choices=[('online', 'Online'), ('cash', 'Cash'), ('bank transfer', 'Bank Transfer')], max_length=50, null=True)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('paid', models.BooleanField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='payment user')),
            ],
        ),
        migrations.CreateModel(
            name='DExtra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.product', verbose_name='extra product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='extra user')),
            ],
        ),
    ]
