# Generated by Django 3.2.3 on 2021-10-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drefund',
            name='reason',
            field=models.CharField(blank=True, choices=[('not delivered', 'Not delivered'), ('leaked', 'Leaked'), ('spoiled', 'Spoiled')], max_length=50, null=True),
        ),
    ]
